server:
    port: 12000
spring:
    application:
        name: tensquare-config
    cloud:
        config:
            server:
                git:
                    uri: https://gitee.com/jonas_von/tensquare.git
    rabbitmq:
        host: 192.168.229.128
management:
    endpoints:
        web:
            exposure:
                include: bus-refresh