server:
    port: 9005
spring:
    application:
        name: tensquare-gathering
    datasource:
        url: jdbc:mysql://192.168.229.128:3306/tensquare_gathering?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: mysql
        show-sql: true
    redis:
        host: 192.168.229.128